#!/usr/bin/env bash
# Regenerate docs/workflows.md from the Arazzo spec using apitapviz (Mermaid + Markdown).
#
# apitapviz (https://github.com/lornajane/apitapviz) is a clone-and-run tool, not
# published to PyPI, so it is pinned to a known commit and run from a local clone.
# The generated page is committed; rerun this script after changing the Arazzo spec.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SPEC="$REPO_ROOT/specs/anncsu-workflow.arazzo.yaml"
OUT="$REPO_ROOT/docs/workflows.md"

APITAPVIZ_COMMIT="3561d1c494c5c7d033551fd362e085937d138ebd"
TOOL_DIR="${APITAPVIZ_DIR:-${TMPDIR:-/tmp}/apitapviz}"

if [ ! -d "$TOOL_DIR/.git" ]; then
  git clone https://github.com/lornajane/apitapviz "$TOOL_DIR"
fi
git -C "$TOOL_DIR" checkout --quiet "$APITAPVIZ_COMMIT" 2>/dev/null || {
  git -C "$TOOL_DIR" fetch --quiet origin
  git -C "$TOOL_DIR" checkout --quiet "$APITAPVIZ_COMMIT"
}
( cd "$TOOL_DIR" && uv sync --quiet )

mermaid="$( cd "$TOOL_DIR" && uv run main.py "$SPEC" --format mermaid )"
markdown="$( cd "$TOOL_DIR" && uv run main.py "$SPEC" --format markdown )"

mkdir -p "$REPO_ROOT/docs"
{
  echo "# ANNCSU Arazzo workflows"
  echo
  echo "<!-- Generated by scripts/gen-docs.sh via apitapviz (pinned ${APITAPVIZ_COMMIT})."
  echo "     Do not edit by hand; rerun the script after changing the Arazzo spec."
  echo "     Step descriptions are domain content from the spec and may be in Italian. -->"
  echo
  echo "## Workflow graph"
  echo
  echo '```mermaid'
  printf '%s\n' "$mermaid"
  echo '```'
  echo
  printf '%s\n' "$markdown"
} > "$OUT"

echo "Wrote $OUT"
