"""Generate docs/workflows.md from the canonical Arazzo spec.

Unlike apitapviz (which labels sections by ``info.title`` and lists every step in
one flat sequence), this renders **one section per workflow** — heading, summary,
a per-workflow Mermaid graph (sequential flow plus goto edges), and the steps with
their operation and outputs. Per-workflow graphs also avoid the global stepId
collision apitapviz hit when two workflows share a step name.

Usage: uv run python scripts/gen_workflows_doc.py [--spec ...] [--out docs/workflows.md]
"""

from __future__ import annotations

from pathlib import Path
from typing import Annotated, Any

import typer
import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SPEC = REPO_ROOT / "specs" / "anncsu-workflow.arazzo.yaml"
DEFAULT_OUT = REPO_ROOT / "docs" / "workflows.md"

_NOTE = (
    "<!-- Generated by scripts/gen_workflows_doc.py from the Arazzo spec. "
    "Do not edit by hand; rerun the script after changing the spec. "
    "Step descriptions are domain content from the spec and may be in Italian. -->"
)


def _node_id(step_id: str) -> str:
    """A Mermaid-safe node id (hyphens are not allowed in bare ids)."""
    return step_id.replace("-", "_")


def _mermaid(workflow: dict[str, Any]) -> list[str]:
    steps = [step["stepId"] for step in workflow["steps"]]
    lines = ["```mermaid", "graph TD"]
    for step_id in steps:
        lines.append(f'  {_node_id(step_id)}["{step_id}"]')
    for current, following in zip(steps, steps[1:], strict=False):
        lines.append(f"  {_node_id(current)} --> {_node_id(following)}")
    for step in workflow["steps"]:
        for action in (step.get("onSuccess") or []) + (step.get("onFailure") or []):
            target = action.get("stepId")
            if action.get("type") == "goto" and target:
                lines.append(f"  {_node_id(step['stepId'])} -. goto .-> {_node_id(target)}")
    lines.append("```")
    return lines


def render(spec: dict[str, Any]) -> str:
    """Render the workflows documentation page as Markdown."""
    lines = ["# ANNCSU Arazzo workflows", "", _NOTE, ""]
    summary = spec.get("info", {}).get("summary")
    if summary:
        lines += [summary.strip(), ""]

    for workflow in spec["workflows"]:
        lines.append(f"## {workflow['workflowId']}")
        lines.append("")
        if workflow.get("summary"):
            lines += [workflow["summary"].strip(), ""]
        lines += _mermaid(workflow)
        lines.append("")
        for index, step in enumerate(workflow["steps"], start=1):
            lines.append(f"### {index}. {step['stepId']}")
            lines.append("")
            if step.get("description"):
                lines += [step["description"].strip(), ""]
            if step.get("operationId"):
                lines.append(f"- Operation: `{step['operationId']}`")
            outputs = list((step.get("outputs") or {}).keys())
            if outputs:
                lines.append(f"- Outputs: {', '.join(outputs)}")
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main(
    spec: Annotated[Path, typer.Option("--spec", help="Arazzo spec file")] = DEFAULT_SPEC,
    out: Annotated[Path, typer.Option("--out", help="Markdown file to write")] = DEFAULT_OUT,
) -> None:
    """Generate the per-workflow documentation page from the Arazzo spec."""
    document = yaml.safe_load(spec.read_text())
    out.write_text(render(document))
    typer.echo(str(out))


if __name__ == "__main__":
    typer.run(main)
